auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /tmp/loki/wal  # ✅ Fix WAL directory permission issue
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index  # ✅ Ensure this path is writable

  filesystem:
    directory: /tmp/loki/chunks  # ✅ Ensure this path is writable

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
